version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/builder"
    update_schedule: "weekly"
    default_reviewers:
      - quotidian-ennui
      - aaron-mcgrath-adp
      - mcwarman
